[package]
name = "clipimg"
version = "0.0.1"
authors = ["Ryo Kitagawa <kitadrum50@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.11"
tempfile = "3.1.0"
