name: Rust

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      name: Build
      run: build --verbose

    - uses: actions-rs/cargo@v1
      name: Test
      run: test --verbose
