name: Rust

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: build
        args: --verbose

    - uses: actions-rs/cargo@v1
      name: Test
      with:
        command: test
        args: --verbose
